# Generated by Django 4.2.4 on 2023-08-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creatted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='upadated_at',
            new_name='updated_at',
        ),
    ]
